# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            两点客
tagline:          '夜已深,梦未眠.'
description:      '两点,奋斗不停!'
url:              http://shelldone.com

author:
  name:           'SunTengfei'
  url:            https://github.com/

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : hippoboy
